### PR TITLE
deprecate holdings creation method

### LINKED ISSUE #53: mark holdings creation deprecated or remove it

### PR DESCRIPTION
**Pull request by ndushay**
## Why was this change made? 🤔

Fixes #53 

to make it clear we're not planning on creating holdings.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

### CODE REVIEW

**Review by mjgiarlo — APPROVED** [review]
LGTM. Do we have a clear enough sense of when we can remove this so that we can ticket it?

**Comment by ndushay** [comment]
> LGTM. Do we have a clear enough sense of when we can remove this so that we can ticket it?

@lwrubel - have any idea of when we can remove the holdings from this gem?   It would be good to ticket it and/or put the date on these messages.   Or not.

**Comment by lwrubel** [comment]
I think the only reason to leave it is if we think the decision/process will be changed at some point in the future from what was decided by the metadata working group last week. Let's just remove it instead of marking it deprecated, then? We'll have this PR and others as a record if we want to put the code back later.

**Comment by mjgiarlo** [comment]
@lwrubel Sounds like a plan. I 💯 support yanking this functionality now.

**Comment by ndushay** [comment]
superseded by https://github.com/sul-dlss/folio_client/pull/57 which removes the holdings method altogether.

**Pull request closed without merging**
